language: python
sudo: required
services:
- docker
before_install:
- docker pull f5devcentral/containthedocs:latest
- chmod +x ./scripts/docker-docs.sh ./scripts/test-docs.sh
install: 
- pip install awscli --upgrade
script:
- ./scripts/docker-docs.sh ./scripts/test-docs.sh
deploy:
# DEPLOY TO STAGING
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: clouddocs.f5networks.net
  local_dir: docs/_build/html
  upload_dir: $AWS_DIR
  on:
    branch: docs-staging
    repo: F5Networks/terraform-provider-bigip-version0.12
# DEPLOY TO PRODUCTION
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: clouddocs.f5.com
  local_dir: docs/_build/html
  upload_dir: $AWS_DIR
  on:
    branch: docs-publish
    repo: F5Networks/terraform-provider-bigip
after_deploy:
  - aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths $AWS_DIR
