sudo: false
language: go

go:
  - 1.9

go_import_path: github.com/f5devcentral/terraform-provider-f5

before_install:
  - go get github.com/hashicorp/terraform
  - go get github.com/mitchellh/gox
  - go get github.com/scottdware/go-bigip
  - go get github.com/aws/aws-sdk-go/aws
  - go get github.com/aws/aws-sdk-go/aws/ec2metadata
  - go get github.com/aws/aws-sdk-go/aws/session
  - go get github.com/aws/aws-sdk-go/service/s3
  - go get github.com/bgentry/speakeasy
  - go get github.com/mattn/go-isatty
  - go get github.com/posener/complete
  - go get github.com/posener/complete/cmd/install
  - go get github.com/armon/go-radix
  - go get golang.org/x/crypto/openpgp/armor
  - go get golang.org/x/crypto/openpgp/errors
  - go get golang.org/x/crypto/openpgp/packet
  - go get golang.org/x/crypto/openpgp/s2k


install:
  - make get-deps

script:
  - make bin

after_success:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: pu+/NBPKLM+6sl76GzuIxsmsp2LBEUY0y2UXEoAVtrY52WbybBtJW8HB+Vqx1QJEdSJCQ48QonkGB5H7M3FuLy9BjCJHm+Na0L3TPoYxMAGtkUWUzz/sErRRQarOJ3HxJCdiBNKZHaY9yPlHYpPYYVO7vgWV8EppP9LuVT7tUW3KRkqqURKqYPfV9hlfBZ1Ik6QB8vqophzZuPWHHqWF2249wO06Lr9B0QV907Cum6RCFOOTzqmwDgc1V0f6JePIOq9RmnkFiSdmTGi+fGFHbkVomjbGE1HR8vPO1XVbRZ3AYQnA1eGKpfjBzWn0NSmcPh79UQRohC3luAHJRIKBuGmDc6dm1dmFh3nicq8T565Vupxxq1YxVG4S3wdr+apk1vM6pA+eHk0l+n1OdTSFmYhFygt6YDx5OWKhCgQyvtYBW3tsMIe7WtfOrkZotFzeQczQoE0mZ7vTW70zPzjnnA2KbDTMdX83cQ0vqZEuufTDFBQ/rbK7CZeAk82rJ4SaLHeCcxcLaDKQobKEYmVtsqA4OIqejQpjqerQK0dg5L8r6e8YJT4jLuEGpktNPGsiOQXNvnU7gChsQRj2Rq2GzU4EvUfCQ1mKjzzFNyT5mkfGUUvBRWytyuwfrSTAbvIGprCg56/x8W7CElSK3ZTbSpZnQqnVicmLZYwYinTTe+4=
  file_glob: true
  file: "target/pkg/*.tar.gz"
  on:
    tags: true
